---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-deploy 
  labels:
    app: facebookk
    env: lab 

spec:
  selector:
    matchLabels:
      app: facebookk 
  replicas: 2  
  template:
    metadata:
      name: fb-pod 
      labels:
        app: facebookk
        env: lab
        tier: frontend 
        version: v1_AC
    spec:
      containers:
        - name: fb-pod-cont
          image: sravan1305/sravankumar:10
          ports:
            - containerPort: 8080
